[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/niche-analyzer/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/affiliate-marketing-calculator/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Handle SPA routing for each app
[[redirects]]
  from = "/affiliate-marketing-calculator/*"
  to = "/affiliate-marketing-calculator/index.html"
  status = 200

[[redirects]]
  from = "/niche-analyzer/*"
  to = "/niche-analyzer/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Rewrite rules for assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/niche-analyzer/assets/*"
  to = "/niche-analyzer/assets/:splat"
  status = 200

[[redirects]]
  from = "/affiliate-marketing-calculator/assets/*"
  to = "/affiliate-marketing-calculator/assets/:splat"
  status = 200
